<Project>
  <Import Project="Versions\ProductVersion.props" />
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Product>Orbit Navigator</Product>
    <Authors>Orbit Nav Pub</Authors>
    <Company>Orbit Nav Pub</Company>
    <Copyright>Copyright © 2026 Orbit Nav Pub</Copyright>
    <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <DebugType>embedded</DebugType>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
</Project>
